### ISSUE TITLE
A tiny question about the data processing

### ISSUE THREAD

**Issue by mmmmimic** [ai-med/DAFT#4]
Dear authors,

Thanks for the great work! 

I am writing to ask you about the tabular data processing strategy in your paper. It is very interesting to add a binary variable indicating the missingness of a tabular value. I kindly wonder besides the binary variable, how did you fill in the value of the missing tabular variables? Should it be somewhat 0 or imputed by interpolation/KNN? I am asking since I suppose we might need to feed them into the network.

**Comment by lupus83** [comment]
Thank you for being so interested in our work!

As you assumed, we've filled the feature's value with 0 if it was missing at a certain visit.

**Comment by mmmmimic** [comment]
Thank you so much!
