### ISSUE TITLE
Issue Regarding Data Loading

### ISSUE THREAD

**Issue by J-like** [ai-med/DAFT#5]
Hello, author. 
I have processed my data into the HDF5 data structure as described in your README. However, when running the **_def _load(self, filename, dataset_name, roi="Left-Hippocampus")_** function, I always encounter the error KeyError: _**"Unable to open object (object 'Left-Hippocampus' doesn't exist)**_" when reaching the line **_meta = self._get_meta_data(hf["stats"][roi][dataset_name])._** To address this, I added a sub-group named "Left-Hippocampus" in the "stats" group and set its "vol_with_bg" value to (64, 64, 64). However, this resulted in another error: **_AttributeError: 'Dataset' object has no attribute 'items'._** 
So, I would like to seek your advice again regarding the data structure. Is there a need to add something specific in the "stats" group?

**Comment by ndavoudi** [comment]
Hi
I encounter the same issue as mentioned above. Could you please clarify it? 
Thanks

**Comment by lupus83** [comment]
Hi and sorry about that bug.

I've come up with a quick fix available on branch `fix_issue_5` (commit 5ef3e70).
However, I'll have to test that before merging it into `main`, so please consider this experimental.

Feedback on this fix is highly appreciated!

**Comment by lupus83** [comment]
solved in PR #7
