### ISSUE TITLE
Issue regarding data loading 

### ISSUE THREAD

**Issue by ndavoudi** [ai-med/DAFT#6]
Hi
I have processed my data into the HDF5 data structure as described in your README. However, when running the _def load(self, filename, dataset_name, roi="Left-Hippocampus") function, I always encounter the error KeyError: "Unable to open object (object 'Left-Hippocampus' doesn't exist)" when reaching the line _meta = self.get_meta_data(hf["stats"][roi][dataset_name]). 
I appreciate your response for solving this issue.

**Comment by lupus83** [comment]
Hi and sorry about that bug.

I've come up with a quick fix available on branch 5ef3e70.
However, I'll have to test that in the future before merging it into main, so please consider it experimental.

**Comment by lupus83** [comment]
Please refer to [this](https://github.com/ai-med/DAFT/issues/5#issuecomment-1963080640) answer in issue #5.
